import Head from 'next/head';

const Home = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main>
      <h1 className="text-4xl font-bold">Welcome to Next.js!</h1>
    </main>
  </>
);

export default Home;
