import Head from 'next/head';
import Image from 'next/image';

import landingBG from '../../public/images/landing_background.png';
import Hero from '../components/Hero/Hero';
import ghost, { ILandingContent } from '../lib/services/ghost';

interface IHeroProps {
  content: ILandingContent;
}

const Home = ({ content }: IHeroProps) => {
  const { hero } = content;
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <Image
          src={landingBG}
          alt="Background of Landing Page"
          fill
          className="-z-10 h-screen object-cover object-right-top"
        />
        <main className="flex h-full w-full flex-col">
          <Hero hero={hero} />
        </main>
      </>
    </>
  );
};

export const getStaticProps = async () => {
  const content = await ghost.getLandingPosts();

  return {
    props: {
      content,
    },
  };
};

export default Home;
